[project]
name = "style-variant-builder"
version = "0.1.0"
description = "Create Citation Style Language (CSL) style variants using a template."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["lxml>=6.0.0", "lxml-stubs>=0.5.1"]
